"""IK solver tests, both solvers held to the same behavioural contract.

The unreachable-target cases carry the most weight. This arm's joint space is
about 0.01% of a full-rotation six-axis arm, so most requested poses are
genuinely unreachable and "return the closest reachable pose" is the normal
path rather than an edge case.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from arm_ik import IKStatus, RobotModel, SolverConfig

URDF = Path(__file__).resolve().parents[1] / "description" / "arm.urdf"
SOLVERS = ["dls", "least_squares"]


@pytest.fixture(scope="module")
def robot() -> RobotModel:
    return RobotModel.from_urdf(URDF)


def reachable_targets(robot: RobotModel, count: int = 12) -> list[np.ndarray]:
    """Poses generated by forward kinematics, so a solution provably exists."""
    rng = np.random.default_rng(4242)
    return [robot.fk(robot.random_configuration(rng)) for _ in range(count)]


@pytest.mark.parametrize("solver", SOLVERS)
def test_recovers_forward_kinematics_poses(robot: RobotModel, solver: str) -> None:
    for pose in reachable_targets(robot):
        result = robot.ik(target=pose, solver=solver)
        assert result.status is IKStatus.CONVERGED, result.status
        assert result.position_error < 1e-4
        assert result.orientation_error < 1e-3
        assert robot.within_limits(result.q)
        # The returned q must actually produce the requested pose.
        assert np.allclose(robot.fk(result.q), pose, atol=1e-4)


@pytest.mark.parametrize("solver", SOLVERS)
def test_solution_respects_joint_limits(robot: RobotModel, solver: str) -> None:
    rng = np.random.default_rng(7)
    for _ in range(10):
        target = rng.uniform(-0.4, 0.4, 3)
        result = robot.ik(position=target, solver=solver)
        assert robot.within_limits(result.q, tol=1e-7)


@pytest.mark.parametrize("solver", SOLVERS)
def test_far_target_reports_unreachable_not_failure(
    robot: RobotModel, solver: str
) -> None:
    """A target 1.5 m away must be classified, and still return the nearest pose."""
    target = np.array([1.5, 0.0, 0.0])
    result = robot.ik(position=target, solver=solver)
    assert result.status is IKStatus.OUT_OF_REACH
    assert not result.status.is_usable
    assert robot.within_limits(result.q)

    # The returned pose must be a genuine optimum, not merely a stopping point:
    # no sampled configuration may get closer to the target. Asserting a fraction
    # of the outer reach bound would be wrong -- the arm's maximum-radius pose
    # points elsewhere, so the closest approach toward +x is well inside it.
    rng = np.random.default_rng(99)
    best = min(
        np.linalg.norm(robot.fk(robot.random_configuration(rng))[:3, 3] - target)
        for _ in range(500)
    )
    assert result.position_error <= best + 1e-9


def test_both_solvers_agree_on_the_nearest_reachable_pose(robot: RobotModel) -> None:
    """Independent formulations should locate the same boundary point."""
    target = np.array([1.5, 0.0, 0.0])
    errs = [
        robot.ik(position=target, solver=name).position_error for name in SOLVERS
    ]
    assert np.isclose(errs[0], errs[1], rtol=1e-3), errs


def test_position_only_mode_ignores_orientation(robot: RobotModel) -> None:
    """Dropping the orientation weight is the main lever for this arm's narrow wrist."""
    pose = robot.fk(robot.random_configuration(np.random.default_rng(11)))
    tilted = pose.copy()
    tilted[:3, :3] = np.eye(3)  # an orientation the wrist cannot reach

    strict = robot.ik(target=tilted)
    loose = robot.ik(target=tilted, config=SolverConfig(orientation_weight=0.0))

    assert loose.position_error < 1e-5
    assert loose.position_error <= strict.position_error


def test_good_seed_converges_without_restarts(robot: RobotModel) -> None:
    q_true = robot.random_configuration(np.random.default_rng(3))
    result = robot.ik(target=robot.fk(q_true), seed=q_true)
    assert result.status is IKStatus.CONVERGED
    assert result.restarts_used == 0
    assert result.iterations <= 5


def test_inner_dead_zone_is_unreachable(robot: RobotModel) -> None:
    """The arm cannot reach a point beside its own base."""
    near, _ = robot.reach_bounds
    result = robot.ik(position=[0.0, 0.0, 0.0])
    assert result.status is IKStatus.OUT_OF_REACH
    assert near > 0.0


def test_result_is_immutable(robot: RobotModel) -> None:
    result = robot.ik(position=[0.1, 0.0, 0.2])
    with pytest.raises((AttributeError, TypeError)):
        result.q = np.zeros(6)  # type: ignore[misc]
